In [7]:
import pandas as pd
import numpy as np
data=pd.read_csv('featureimportance.csv',header=0,sep=',')
#data.columns = ['Decision Tree','Logistic Regression','RFE']

In [8]:
data

,Decision Tree,Logistic Regression,RFE
0,duration,euribor3m,poutcome_success
1,nr.employed,duration,day_of_week_mon
2,cons.conf.idx,poutcome_success,education_unknown
3,contact,cons.conf.idx,education_university.degree
4,euribor3m,education_illiterate,education_professional.course
5,age,cons.price.idx,education_high.school
6,cons.price.idx,month_mar,education_basic.9y
7,campaign,age,education_basic.6y
8,education_high.school,default_yes,job_housemaid
9,day_of_week_mon,housing_unknown,job_blue-collar
10,day_of_week_thu,loan_unknown,day_of_week_wed
11,emp.var.rate,job_student,day_of_week_tue
12,day_of_week_tue,month_dec,day_of_week_thu
13,education_university.degree,job_unemployed,month_nov
14,pdays,job_unknown,job_unknown
15,day_of_week_wed,poutcome_nonexistent,job_unemployed
16,housing_yes,pdays_no_contact,job_services
17,education_professional.course,campaign,job_entrepreneur
18,month_jul,loan_yes,job_self-employed
19,marital_married,job_technician,contact
20,education_basic.9y,job_services,month_may
21,marital_single,job_self-employed,month_jun
22,job_blue-collar,pdays,month_jul
23,month_oct,marital_unknown,month_aug
24,previous,job_retired,default_unknown
25,job_technician,housing_yes,marital_single
26,poutcome_nonexistent,month_oct,marital_married
27,default_unknown,job_entrepreneur,job_technician
28,loan_yes,month_jun,job_retired
29,job_management,month_sep,job_management
30,education_unknown,month_jul,month_sep
31,job_services,job_management,month_oct
32,month_nov,default_unknown,month_mar
33,job_self-employed,education_unknown,loan_yes
34,education_basic.6y,education_basic.6y,loan_unknown
35,poutcome_success,job_housemaid,housing_yes
36,month_aug,marital_single,housing_unknwon
37,job_housemaid,month_aug,job_unemployed
38,job_unemployed,day_of_week_wed,job_student
39,job_retired,previous,previous
40,month_may,marital_married,emp.var.rate
41,job_entrepreneur,day_of_week_tue,month_dec
42,job_student,day_of_week_mon,job_unemployed
43,month_jun,contact,nr.employed
44,loan_unknown,month_nov,euribor3m
45,month_sep,education_basic.9y,cons.conf.idx
46,pdays_no_contact,education_professional.course,cons.price.idx
47,month_dec,day_of_week_thu,pdays
48,job_unknown,month_may,campaign
49,housing_unknown,job_blue-collar,duration
50,month_mar,education_university.degree,pdays_no_contact
51,education_illiterate,marital_unknown,marital_unknown
52,marital_unknown,emp.var.rate,education_illiterate
53,default_yes,nr.employed,default_yes